FROM rust:1.85-slim as build

WORKDIR /app

RUN apt update 
RUN apt install -y build-essential pkg-config libssl-dev cmake

COPY ./Cargo.toml ./Cargo.toml
COPY ./operator ./operator
COPY ./proxy ./proxy

RUN cargo build --release

FROM debian:stable-slim
COPY --from=build /app/target/release/controller /usr/local/bin/controller
ENTRYPOINT [ "controller" ]
